version: "3"

services: 
    php:
        container_name: php-fpm
        build:
            context: .
        volumes: 
            - "./:/var/www"            
        ports:
            - "9000:9000"
        restart: always
        
    nginx:
        image: nginx
        container_name: nginx-server
        restart: always
        volumes: 
            - "./:/var/www"   
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on: 
            - php
        ports: 
            - "8000:80"
        links: 
            - php